apiVersion: v1
kind: Pod
metadata:
  name: random-scheduler
  namespace: default
spec:
  serviceAccountName: scheduler
  containers:
  - image: gcr.io/grounded-chain-252205/random-scheduler:v0.1
    name: random-scheduler
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m

